- name: Install required packages
  community.general.pacman:
    name:
      - alacritty
      - alsa-utils
      - asoundconf
      - feh
      - gnu-free-fonts
      - i3-gaps
      - i3status
      - pulseaudio
      - pulseaudio-alsa
      - python-i3ipc
      - python-pywal
      - rofi
      - xclip
      - xdg-utils
      - org-server
      - xorg-xinit
      - xorg-xinput
      - xss-lock
    state: latest
    update_cache: yes
  become: yes

- name: Install required packages (AUR)
  community.general.pacman:
    executable: yay
    name:
      - alternating-layouts-git
      - picom-jonaburg-git
      - polybar
      - python-colorthief
      - xcwd
    state: latest
    update_cache: yes

- name: Copy configuration files
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ home_dir }}/.config/{{ item }}"
    mode: preserve
  loop:
    - src: alacritty
      dest: "{{ home_dir }}/.config/alacritty"
    - src: dconf
      dest: "{{ home_dir }}/.config/dconf"
    - src: feh
      dest: "{{ home_dir }}/.config/feh"
    - src: i3
      dest: "{{ home_dir }}/.config/i3"
    - src: mouse
      dest: "{{ home_dir }}/.config/mouse"
    - src: picom
      dest: "{{ home_dir }}/.config/picom"
    - src: polybar
      dest: "{{ home_dir }}/.config/polybar"
    - src: rofi
      dest: "{{ home_dir }}/.config/rofi"
    - src: wal
      dest: "{{ home_dir }}/.config/wal"
    - src: xinitrc
      dest: "{{ home_dir }}/.xinitrc"
