- name: Install packages (Arch)
  ansible.builtin.include: arch.yml
  when: ansible_facts["distribution"] == "Archlinux"

- name: Copy user configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ home_dir }}/.config/{{ item.dest }}"
    mode: preserve
  loop:
    - src: alacritty
      dest: "{{ home_dir }}/.config/alacritty"
    - src: bluetooth
      dest: "{{ home_dir }}/.config/bluetooth"
    - src: dconf
      dest: "{{ home_dir }}/.config/dconf"
    - src: feh
      dest: "{{ home_dir }}/.config/feh"
    - src: i3
      dest: "{{ home_dir }}/.config/i3"
    - src: mouse
      dest: "{{ home_dir }}/.config/mouse"
    - src: picom
      dest: "{{ home_dir }}/.config/picom"
    - src: polybar
      dest: "{{ home_dir }}/.config/polybar"
    - src: redshift
      dest: "{{ home_dir }}/.config/redshift"
    - src: rofi
      dest: "{{ home_dir }}/.config/rofi"
    - src: wal
      dest: "{{ home_dir }}/.config/wal"
    - src: xinitrc
      dest: "{{ home_dir }}/.xinitrc"

- name: Copy global configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: preserve
    owner: root
    group: root
  loop:
    - src: geoclue.conf
      dest: /etc/geoclue/geoclue.conf
  become: yes

- name: Add user to groups
  ansible.builtin.user:
    append: yes
    groups:
      - lp
    name: "{{ lookup('env', 'USER') }}"

- name: Configure systemd units
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - bluetooth
