
[cursor]
blink_interval = 750
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Block"

# [env]
# TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[terminal.shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.975

[window.padding]
x = 8
y = 8

[general]
import = ["~/.config/alacritty/dracula.toml"]

[terminal]
