- name: Install required packages
  community.general.pacman:
    name:
      - git
      - man-db
      - neofetch
      - node
      - ranger
      - tmux
      - unp
      - unzip
      - vim
      - yarn
      - zsh
    state: latest
    update_cache: yes
  become: yes

- name: Install required packages (AUR)
  community.general.pacman:
    executable: yay
    name:
      - tmux-plugin-manager
      - ttf-meslo-nerd-font-powerlevel10k
      - vim-plug
    state: latest
    update_cache: yes
