- name: Install packages (Arch)
  ansible.builtin.include_tasks: arch.yml
  when: ansible_facts["distribution"] == "Archlinux"

- name: Install packages (Debian)
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts["distribution"] == "Debian"

- name: Install packages (MacOSX)
  ansible.builtin.include_tasks: mac-osx.yml
  when: ansible_facts["distribution"] == "MacOSX"

- name: Check for oh-my-zsh
  ansible.builtin.stat:
    path: "{{ home_dir }}/.oh-my-zsh"
  register: oh_my_zsh

- name: Install oh-my-zsh
  when: not oh_my_zsh.stat.exists
  block:

    - name: Download oh-my-zsh install script
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/install-zsh.sh

    - name: Install oh-my-zsh
      ansible.builtin.shell:
        cmd: sh -c /tmp/install-zsh.sh

- name: Create required directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ home_dir }}/.config/ranger/plugins"
    - "{{ home_dir }}/.vim"

- name: Copy configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    directory_mode: "0755"
  loop:
    - src: aliases.sh
      dest: "{{ home_dir }}/.aliases.sh"
    - src: bash_profile
      dest: "{{ home_dir }}/.bash_profile"
    - src: bashrc
      dest: "{{ home_dir }}/.bashrc"
    - src: gitconfig
      dest: "{{ home_dir }}/.gitconfig"
    - src: inputrc
      dest: "{{ home_dir }}/.inputrc"
    - src: p10k.zsh
      dest: "{{ home_dir }}/.p10k.zsh"
    - src: rc.conf
      dest: "{{ home_dir }}/.config/ranger/rc.conf"
    - src: tmux.conf
      dest: "{{ home_dir }}/.tmux.conf"
    - src: vimrc
      dest: "{{ home_dir }}/.vim/vimrc"
    - src: zshrc
      dest: "{{ home_dir }}/.zshrc"

- name: Update and install vim plugins
  ansible.builtin.shell:
    cmd: vim +PlugUpgrade +PlugClean +PlugUpdate +PlugInstall +qall

- name: Install ranger powerlevel10k
  ansible.builtin.git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ home_dir }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
    single_branch: yes

- name: Install ranger devicons
  ansible.builtin.git:
    repo: https://github.com/alexanderjeurissen/ranger_devicons.git
    dest: "{{ home_dir }}/.config/ranger/plugins/ranger_devicons"
    depth: 1
    single_branch: yes
